/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */


var m_count = 0;
m_items = new Array(
"<h3>ti.catalog.c6000</h3>",
"<h5>Kepler</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2240000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2250000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2260000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2270000         </td></tr>",
   "<tr><td> 8        </td><td> Timer8   </td><td> 0x2280000         </td></tr>",
   "<tr><td> 9        </td><td> Timer9   </td><td> 0x2290000         </td></tr>",
   "<tr><td> 10        </td><td> Timer10   </td><td> 0x22a0000         </td></tr>",
   "<tr><td> 11        </td><td> Timer11   </td><td> 0x22b0000         </td></tr>",
   "<tr><td> 12        </td><td> Timer12   </td><td> Unsupported         </td></tr>",
   "<tr><td> 13        </td><td> Timer13   </td><td> Unsupported         </td></tr>",
   "<tr><td> 14        </td><td> Timer14   </td><td> 0x22e0000         </td></tr>",
   "<tr><td> 15        </td><td> Timer15   </td><td> 0x22f0000         </td></tr>",
 "</table>",
"<h5>OMAPL137</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>OMAPL138</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1f0c000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x1f0d000         </td></tr>",
 "</table>",
"<h5>TMS320C6421</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320C6424</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320C6452</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2044400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2044800         </td></tr>",
 "</table>",
"<h5>TMS320C6454</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2940000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2980000         </td></tr>",
 "</table>",
"<h5>TMS320C6455</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2940000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2980000         </td></tr>",
 "</table>",
"<h5>TMS320C6457</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2940000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2980000         </td></tr>",
 "</table>",
"<h5>TMS320C6472</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x25e0000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x25f0000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2600000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2610000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2620000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2630000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2640000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2650000         </td></tr>",
   "<tr><td> 8        </td><td> Timer8   </td><td> 0x2660000         </td></tr>",
   "<tr><td> 9        </td><td> Timer9   </td><td> 0x2670000         </td></tr>",
   "<tr><td> 10        </td><td> Timer10   </td><td> 0x2680000         </td></tr>",
   "<tr><td> 11        </td><td> Timer11   </td><td> 0x2690000         </td></tr>",
 "</table>",
"<h5>TMS320C6474</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2910000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2920000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2930000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2940000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2950000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2960000         </td></tr>",
 "</table>",
"<h5>TMS320C6654</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> Unsupported         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> Unsupported         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> Unsupported         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> Unsupported         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> Unsupported         </td></tr>",
 "</table>",
"<h5>TMS320C6655</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> Unsupported         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> Unsupported         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> Unsupported         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> Unsupported         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> Unsupported         </td></tr>",
 "</table>",
"<h5>TMS320C6657</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> Unsupported         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> Unsupported         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> Unsupported         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> Unsupported         </td></tr>",
 "</table>",
"<h5>TMS320C6670</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2240000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2250000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2260000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2270000         </td></tr>",
 "</table>",
"<h5>TMS320C6671</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2280000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2290000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x22a0000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x22b0000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x22c0000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x22d0000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x22e0000         </td></tr>",
   "<tr><td> 8        </td><td> Timer8   </td><td> 0x22f0000         </td></tr>",
 "</table>",
"<h5>TMS320C6672</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
 "</table>",
"<h5>TMS320C6674</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2240000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2250000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2260000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2270000         </td></tr>",
 "</table>",
"<h5>TMS320C6678</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2240000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2250000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2260000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2270000         </td></tr>",
   "<tr><td> 8        </td><td> Timer8   </td><td> 0x2280000         </td></tr>",
   "<tr><td> 9        </td><td> Timer9   </td><td> 0x2290000         </td></tr>",
   "<tr><td> 10        </td><td> Timer10   </td><td> 0x22a0000         </td></tr>",
   "<tr><td> 11        </td><td> Timer11   </td><td> 0x22b0000         </td></tr>",
   "<tr><td> 12        </td><td> Timer12   </td><td> 0x22c0000         </td></tr>",
   "<tr><td> 13        </td><td> Timer13   </td><td> 0x22d0000         </td></tr>",
   "<tr><td> 14        </td><td> Timer14   </td><td> 0x22e0000         </td></tr>",
   "<tr><td> 15        </td><td> Timer15   </td><td> 0x22f0000         </td></tr>",
 "</table>",
"<h5>TMS320C6742</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1f0c000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x1f0d000         </td></tr>",
 "</table>",
"<h5>TMS320C6743</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320C6745</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320C6746</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1f0c000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x1f0d000         </td></tr>",
 "</table>",
"<h5>TMS320C6747</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320C6748</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1f0c000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x1f0d000         </td></tr>",
 "</table>",
"<h5>TMS320CDM415</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320CDM420</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320CDM421</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320CDM425</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320CDM426</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320CDM6431</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320CDM6433</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320CDM6435</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320CDM6437</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320CDM6446</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320CDM6467</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320CDM647</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2044400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2044800         </td></tr>",
 "</table>",
"<h5>TMS320CDM648</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2044400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2044800         </td></tr>",
 "</table>",
"<h5>TMS320CTCI6482</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2940000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2980000         </td></tr>",
 "</table>",
"<h5>TMS320CTCI6484</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2940000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2980000         </td></tr>",
 "</table>",
"<h5>TMS320CTCI6486</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x25e0000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x25f0000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2600000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2610000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2620000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2630000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2640000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2650000         </td></tr>",
   "<tr><td> 8        </td><td> Timer8   </td><td> 0x2660000         </td></tr>",
   "<tr><td> 9        </td><td> Timer9   </td><td> 0x2670000         </td></tr>",
   "<tr><td> 10        </td><td> Timer10   </td><td> 0x2680000         </td></tr>",
   "<tr><td> 11        </td><td> Timer11   </td><td> 0x2690000         </td></tr>",
 "</table>",
"<h5>TMS320CTCI6487</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2910000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2920000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2930000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2940000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2950000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2960000         </td></tr>",
 "</table>",
"<h5>TMS320CTCI6488</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2910000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2920000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2930000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2940000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2950000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2960000         </td></tr>",
 "</table>",
"<h5>TMS320DA802</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA803</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA804</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA805</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA807</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA808</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA810</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA828</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA830</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA840</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1f0c000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x1f0d000         </td></tr>",
 "</table>",
"<h5>TMS320DA850</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1f0c000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x1f0d000         </td></tr>",
 "</table>",
"<h5>TMS320TCI6485</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2910000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2920000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2930000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2940000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2950000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2960000         </td></tr>",
 "</table>",
"<h5>TMS320TCI6489</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2910000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2920000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2930000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2940000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2950000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2960000         </td></tr>",
 "</table>",
"<h5>TMS320TCI6608</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2240000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2250000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2260000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2270000         </td></tr>",
   "<tr><td> 8        </td><td> Timer8   </td><td> 0x2280000         </td></tr>",
   "<tr><td> 9        </td><td> Timer9   </td><td> 0x2290000         </td></tr>",
   "<tr><td> 10        </td><td> Timer10   </td><td> 0x22a0000         </td></tr>",
   "<tr><td> 11        </td><td> Timer11   </td><td> 0x22b0000         </td></tr>",
   "<tr><td> 12        </td><td> Timer12   </td><td> 0x22c0000         </td></tr>",
   "<tr><td> 13        </td><td> Timer13   </td><td> 0x22d0000         </td></tr>",
   "<tr><td> 14        </td><td> Timer14   </td><td> 0x22e0000         </td></tr>",
   "<tr><td> 15        </td><td> Timer15   </td><td> 0x22f0000         </td></tr>",
 "</table>",
"<h5>TMS320TCI6614</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2240000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2250000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2260000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2270000         </td></tr>",
 "</table>",
"<h5>TMS320TCI6616</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2240000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2250000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2260000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2270000         </td></tr>",
 "</table>",
"<h5>TMS320TCI6618</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2240000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2250000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2260000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2270000         </td></tr>",
 "</table>",
"<h5>TMS320TCI6634</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2240000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2250000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2260000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2270000         </td></tr>",
   "<tr><td> 8        </td><td> Timer8   </td><td> 0x2280000         </td></tr>",
   "<tr><td> 9        </td><td> Timer9   </td><td> 0x2290000         </td></tr>",
   "<tr><td> 10        </td><td> Timer10   </td><td> 0x22a0000         </td></tr>",
   "<tr><td> 11        </td><td> Timer11   </td><td> 0x22b0000         </td></tr>",
   "<tr><td> 12        </td><td> Timer12   </td><td> Unsupported         </td></tr>",
   "<tr><td> 13        </td><td> Timer13   </td><td> Unsupported         </td></tr>",
   "<tr><td> 14        </td><td> Timer14   </td><td> 0x22e0000         </td></tr>",
   "<tr><td> 15        </td><td> Timer15   </td><td> 0x22f0000         </td></tr>",
 "</table>",
"<h5>TMS320TCI6636</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2240000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2250000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2260000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2270000         </td></tr>",
   "<tr><td> 8        </td><td> Timer8   </td><td> 0x2280000         </td></tr>",
   "<tr><td> 9        </td><td> Timer9   </td><td> 0x2290000         </td></tr>",
   "<tr><td> 10        </td><td> Timer10   </td><td> 0x22a0000         </td></tr>",
   "<tr><td> 11        </td><td> Timer11   </td><td> 0x22b0000         </td></tr>",
   "<tr><td> 12        </td><td> Timer12   </td><td> Unsupported         </td></tr>",
   "<tr><td> 13        </td><td> Timer13   </td><td> Unsupported         </td></tr>",
   "<tr><td> 14        </td><td> Timer14   </td><td> 0x22e0000         </td></tr>",
   "<tr><td> 15        </td><td> Timer15   </td><td> 0x22f0000         </td></tr>",
 "</table>",
"<h5>TMS320TCI6638</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x2200000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x2210000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x2220000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x2230000         </td></tr>",
   "<tr><td> 4        </td><td> Timer4   </td><td> 0x2240000         </td></tr>",
   "<tr><td> 5        </td><td> Timer5   </td><td> 0x2250000         </td></tr>",
   "<tr><td> 6        </td><td> Timer6   </td><td> 0x2260000         </td></tr>",
   "<tr><td> 7        </td><td> Timer7   </td><td> 0x2270000         </td></tr>",
   "<tr><td> 8        </td><td> Timer8   </td><td> 0x2280000         </td></tr>",
   "<tr><td> 9        </td><td> Timer9   </td><td> 0x2290000         </td></tr>",
   "<tr><td> 10        </td><td> Timer10   </td><td> 0x22a0000         </td></tr>",
   "<tr><td> 11        </td><td> Timer11   </td><td> 0x22b0000         </td></tr>",
   "<tr><td> 12        </td><td> Timer12   </td><td> Unsupported         </td></tr>",
   "<tr><td> 13        </td><td> Timer13   </td><td> Unsupported         </td></tr>",
   "<tr><td> 14        </td><td> Timer14   </td><td> 0x22e0000         </td></tr>",
   "<tr><td> 15        </td><td> Timer15   </td><td> 0x22f0000         </td></tr>",
 "</table>",
"<h3>ti.catalog.arm</h3>",
"<h5>AM1705</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>AM1707</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>AM1806</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1f0c000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x1f0d000         </td></tr>",
 "</table>",
"<h5>AM1808</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1f0c000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x1f0d000         </td></tr>",
 "</table>",
"<h5>OMAPL108</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1f0c000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x1f0d000         </td></tr>",
 "</table>",
"<h5>OMAPL118</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1f0c000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x1f0d000         </td></tr>",
 "</table>",
"<h5>OMAPL137</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>OMAPL138</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1f0c000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x1f0d000         </td></tr>",
 "</table>",
"<h5>TMS320CDM510</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1c21c00         </td></tr>",
 "</table>",
"<h5>TMS320CDM6446</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320CDM6467</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320DA805</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA807</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA808</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA810</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA828</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA830</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
 "</table>",
"<h5>TMS320DA850</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c20000         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21000         </td></tr>",
   "<tr><td> 2        </td><td> Timer2   </td><td> 0x1f0c000         </td></tr>",
   "<tr><td> 3        </td><td> Timer3   </td><td> 0x1f0d000         </td></tr>",
 "</table>",
"<h5>TMS320DM355</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<h5>TMS320DM365</h5>",
"<table border=1 cellpadding=3>",
 "<colgroup span=1></colgroup> <colgroup span=5 align=center></colgroup>",
   "<tr><th> Timer ID </th><th> Timer Name </th><th> Timer Base Address </th></tr>",
   "<tr><td> 0        </td><td> Timer0   </td><td> 0x1c21400         </td></tr>",
   "<tr><td> 1        </td><td> Timer1   </td><td> 0x1c21800         </td></tr>",
 "</table>",
"<!-- -->"
);

// gen below code only 1 time
while (m_count < m_items.length) {
    document.write(m_items[m_count]);
    m_count++;
}
/*
 *  @(#) ti.sysbios.timers.timer64; 2, 0, 0, 0,435; 11-7-2012 12:42:49; /db/vtree/library/trees/avala/avala-r22x/src/ xlibrary

 */

